### ISSUE TITLE
Iteration 2: content for splash page

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#101]
Write it out and give it enough structure to be easily designable

**Comment by jazmynlatimer** [comment]
https://docs.google.com/document/d/1rW-KUm-bn1tVvnKkS3HJB7_836vGKDYR8ww3plCFEvE/edit#heading=h.nd87cjgk7pn6

**Comment by bengolder** [comment]
two versions w & w/o official partnership
