### ISSUE TITLE
Splash page fixes, Round 2

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/clear-my-record#125]
- [x] CMR landing page looks weird on mobile iPhone5 (button too wide for mobile)
- [x] change footer text color to white for visibility
- [x] reduce the number of different font sizes and weights
- [x] test in more browsers
- [x] change "California" to "San Francisco" in header
- [x] change "3 easy steps to enroll" to "3 easy steps to apply"
- [x] make sure url says clear-my-record, not clean-slate
- [x] edit top bar to be a link back to the splash page
- [x] change legitimacy statement to "Clear My Record is a free, non-profit service from Code for America (link to cfa.org) for people with a criminal record in San Francisco"

**Comment by jazmynlatimer** [comment]
![weirdonmobile](https://cloud.githubusercontent.com/assets/5255453/13962312/9318dee4-f01d-11e5-8e03-dbaa1170d9f5.png)

**Comment by bengolder** [comment]
Fixed the button width

**Comment by jazmynlatimer** [comment]
- [ ] change "California" to "San Francisco" in header

- [ ] change footer font color to white

- [ ] change "3 easy steps to enroll" to "3 easy steps to apply"

- [ ] make sure url says clear-my-record, not clean-slate

**Comment by jazmynlatimer** [comment]
Some changes for font sizes, weights, and a few spacing edits:

Universally:
- [ ] H1: 54px, 700w. For mobile, H1 = 40px
- [ ] H2: 26px, 700w
- [ ] btn text: 18px, 500w
- [ ] p: 18px, 500w
- [ ] .container should have padding-bottom: 40px

Section 1:
- [ ] Add padding top of 150px to H1
- [ ] Add .small class to header "Clear My Record | Apply to clear your criminal record in SF"
- [ ] Change subheadline "Reduce or dismiss..." to an H2
- [ ] Add padding top of 70px to credibility note

Section 2:
- [ ] Change .time_expectation "It could take up to one year..." from an H3 an H2 with a font-weight of 500

Section 3:
- [ ] li.opportunities should have a padding-bottom of 10px. For mobile, padding-bottom of 20px

Footer:
- [ ] Text should have font-color #ffffff
- [ ] Links should have font-color #3498D8
- [ ] On hover, links should not change color. They should only underline on hover.

Examples:
<img width="1402" alt="screen shot 2016-03-22 at 4 10 17 pm" src="https://cloud.githubusercontent.com/assets/5255453/13971161/12e4eca8-f04b-11e5-9d2a-2c4345459451.png">
<img width="1384" alt="screen shot 2016-03-22 at 4 10 28 pm" src="https://cloud.githubusercontent.com/assets/5255453/13971162/12e5ce66-f04b-11e5-94b7-04fd1491c3ab.png">
<img width="1371" alt="screen shot 2016-03-22 at 4 28 59 pm" src="https://cloud.githubusercontent.com/assets/5255453/13971176/3b8cc4f0-f04b-11e5-9c66-a80aedae0b61.png">

**Comment by bengolder** [comment]
- [ ] in typeform, fix typo on question asking for "home phome"
- [ ] in typeform, change question "how did you hear about clean slate" to "how did you hear about this program"
- [ ] link to privacy policy in the footer and at the end of the typeform
- [ ] add a link to SF PD's Clean Slate website from section 2 header about SF PD's Clean Slate program http://sfpublicdefender.org/services/clean-slate/
- [ ] add padding, color, & header to Privacy Policy
- [ ] reduce the width of anything that gets too wide.
