### ISSUE TITLE
Launch and trial run of splash page

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#132]

**Comment by jazmynlatimer** [comment]
Questions for launch intercepts: 
- What are people coming here for?
- Where are people coming from?
- Do they match our target users (they have convictions in SF County or are helping someone with convictions in SF County)? If not, what's their situation?

Analytics to track:
- Time spent on landing page
- Conversion rate, and which CTA btn gets the most conversions
- Number of visitors
- Where visitors are coming from
- *If possible, how far people get in the Typeform and where they drop off
- *If possible, time spend on Typeform

***If you talk to a user who has convictions in SF, ask them if they'd be interested in participating in paid research in the next 2 weeks to help us make this site better***

Please log notes here: https://docs.google.com/document/d/1vxo1-3oO--qaASG7QVLa4cf2TTba0qP9wFHgV7uFf5c/edit
