### ISSUE TITLE
Live chat covering typeform navigation

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/clear-my-record#152]
Quick fix (maybe) from usability test - the livechat icon was covering the typeform navigation buttons at the bottom right of the application.

**Comment by jazmynlatimer** [comment]
<img width="1188" alt="screen shot 2016-04-05 at 5 57 24 pm" src="https://cloud.githubusercontent.com/assets/5255453/14302620/e200aa60-fb57-11e5-88a7-4cd1248ed2e7.png">

**Comment by bengolder** [comment]
I think this adds to my reasons to replace typeform
