### ISSUE TITLE
Find contacts who handle batch SF RAP sheets

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#153]
- there are people at both the pub def and police
- the DOJ project might help make contact

**Comment by jazmynlatimer** [comment]
SF police dept - 4th floor - room 475 - Bureau of Identification - 

Requesting your own RAP sheet - fill out pink slip, wait in line - officer looks up rap online and prints it for you

Requesting on clients behalf - PD walks over request forms - Officer fills out yellow slip for each separate request - officer looks up rap online and prints them - PD comes back and picks them up later

Jaz asked if we could send RAP requests over email - officer didn't know, he thinks we can't b/c of security - suggested we talk to the Lieutenant in the main Police dept - the person who is in charge of legal stuff
