### ISSUE TITLE
Get a referral from ECS

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#189]

**Comment by jazmynlatimer** [comment]
- Episcopal Community Service
- Sanctuary Sheter

**Comment by jazmynlatimer** [comment]
ECS is in charge of Sanctuary Shelter. Leticia gave us the contact of their community relations manager.

**Comment by jazmynlatimer** [comment]
MB is going to refer us to their workforce development team. She thinks they'd be better suited to partner with CMR

**Comment by bengolder** [comment]
Deprecating. No longer a priority at this stage in the project.
