### ISSUE TITLE
Get a referral from Checkr

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/clear-my-record#206]

**Comment by jazmynlatimer** [comment]
Rescheduling our call for Tuesday morning. Ben & Jaz strategized to end this with a clear idea of what it will take to get referrals to CMR from Checkr

**Comment by jazmynlatimer** [comment]
They're interested in partnering, but have to get their leadership and customers on board first. Would like us to reconnect with Uber to see if they'd be interested in an official pilot. They're talking with Checkr leadership to see if they can include a link to CMR in user emails.

**Comment by bengolder** [comment]
Deprecating. No longer a priority at this stage in the project.
