### ISSUE TITLE
Schedule input from EBCLC

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/clear-my-record#208]

**Comment by bengolder** [comment]
left a message with EH

**Comment by bengolder** [comment]
sent an email to EH

**Comment by bengolder** [comment]
S from EBCLC just called me. She said that they started Clean Slate services 11 years ago and that many of the other programs were based on theirs. They are excited about having some sort of online application. Meeting set up for 5/13 12:30 pm in Oakland at their offices.
