### ISSUE TITLE
Get referral from Root & Rebound

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/clear-my-record#209]

**Comment by jazmynlatimer** [comment]
Called and left VM to our contact there. Waiting for response.

**Comment by jazmynlatimer** [comment]
ST is on a week long work trip, will look at CMR soon and get back to us about how to get the word out

**Comment by jazmynlatimer** [comment]
Link is now on their website: http://sfgov.org/sfreentry/

**Comment by bengolder** [comment]
Acquisition is no longer a priority, so I'm deprecating this.
