### ISSUE TITLE
Applicant notification prototypes

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#305]

**Comment by jazmynlatimer** [comment]
![img_6167](https://cloud.githubusercontent.com/assets/5255453/17719394/09583c56-63cf-11e6-89eb-9f9001e836f7.jpg)
![img_6166](https://cloud.githubusercontent.com/assets/5255453/17719397/0ad14712-63cf-11e6-96f7-6aac3901ad27.jpg)

**Comment by jazmynlatimer** [comment]
https://invis.io/SF9L1J0T2#/209541299_AppIndex
