### ISSUE TITLE
Finish slides for Jen's presentation deck

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#33]

**Comment by jazmynlatimer** [comment]
![file_001](https://cloud.githubusercontent.com/assets/5255453/13122951/7228e478-d56e-11e5-827a-6532743d0a0c.jpeg)
![file_004](https://cloud.githubusercontent.com/assets/5255453/13122947/7223ffc6-d56e-11e5-98c6-6943269c3255.jpeg)
![file_000](https://cloud.githubusercontent.com/assets/5255453/13122952/7228e18a-d56e-11e5-9ec6-8958c579df50.jpeg)
![file_002](https://cloud.githubusercontent.com/assets/5255453/13122950/722800f8-d56e-11e5-9870-7340bc49ef01.jpeg)
![file_005](https://cloud.githubusercontent.com/assets/5255453/13122948/7227336c-d56e-11e5-9e60-95244129813f.jpeg)
![file_003](https://cloud.githubusercontent.com/assets/5255453/13122949/72279a8c-d56e-11e5-81ad-c688ab6224ac.jpeg)
