### ISSUE TITLE
UX/design update on all CMR views

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/clear-my-record#343]
Go through product and make UX/Design updates on all pages. Recommendations in this doc: https://docs.google.com/document/d/1R1MFvU6WK4muDxD2zyjImgIgl_yEZyGlvKnrNPrNdBM/edit

**Comment by jazmynlatimer** [comment]
- [ ] landing page
- [ ] application
- [ ] confirmation page
- [ ] privacy page
- [ ] Applications index
- [ ] Login
- [ ] Org Admin
- [ ] Application view
- [ ] Bungle Application view
- [ ] Org admin settings

**Comment by TiffanyAndrews** [comment]
This issue was moved to codeforamerica/intake#552
