### ISSUE TITLE
Clarify what we would need from any participating County

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#38]
What would we need to know?

* Who files clean slate petitions?
* Is there a filling limit?
* Who checks state-level rap sheet for eligibility?

Questions for participating counties:
https://docs.google.com/a/codeforamerica.org/document/d/19L9NMsjKNUuwYXaI6d7anfNyb6i0J5UWZgNZlLg9mHg/edit?usp=drive_web

**Comment by jazmynlatimer** [comment]
https://docs.google.com/document/d/1W07N3WQcMtPPdwgbyIsPF5Tzsq0kGMGn6kV2Id-A1g0/edit
