### ISSUE TITLE
Facebook preview image of the site is maybe blank?

### ISSUE THREAD

**Issue by daguar** [codeforamerica/clear-my-record#380]
Just flagging, as I shared on Facebook and got this:

![screen shot 2016-09-28 at 12 24 43 pm](https://cloud.githubusercontent.com/assets/994938/18928836/b7b7c276-8576-11e6-9e09-35e18429887e.png)

Obviously not a huge deal, but might be a quick fix.

**Comment by bengolder** [comment]
mmm, thanks for reporting it Dave!

**Comment by bengolder** [comment]
The image is just a white CfA logo on transparent background. We just need to point to the correct asset.
