### ISSUE TITLE
Make comps of legal aid & pub defender referral sign up

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#4]

**Comment by jazmynlatimer** [comment]
<img width="805" alt="screen shot 2016-02-09 at 4 32 39 pm" src="https://cloud.githubusercontent.com/assets/5255453/12935466/ca847f1c-cf4a-11e5-9a2a-15f58ab4fa46.png">
<img width="801" alt="screen shot 2016-02-09 at 4 32 45 pm" src="https://cloud.githubusercontent.com/assets/5255453/12935465/ca824efe-cf4a-11e5-84f5-0158cae94f96.png">
<img width="803" alt="screen shot 2016-02-09 at 4 32 50 pm" src="https://cloud.githubusercontent.com/assets/5255453/12935467/ca84e218-cf4a-11e5-8be8-b765ed4babd4.png">
