### ISSUE TITLE
clarify & summarize the breadth of clean slate mechanisms

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#41]
Define and understand these remedies
- 1203.4/ 1203.4(a) Motions
- 1203.3 Motions
- 851.8 Timeliness
- 851.8 Substantive
- 17(b) Motions
- Certificate of Rehabilitation
- 11594 Motions
- 851.7PC
- 851.90 Motions
- 849.5 Motions/Order
- 11361.5 Motions
- Fines/Fees Motions
- Revert APD to Court Probation
- 17(d) Reduce Misd to Infraction
- Prop 47 (11.70.18PC)

**Comment by TiffanyAndrews** [comment]
This issue was moved to codeforamerica/intake#560
