### ISSUE TITLE
Fresno County Question edits

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/clear-my-record#476]
1.MSR and PRCS should be added to the question of “Are you on probation or parole”
2. Add a statement between “do you understand it might take a few months” and “Do you give the PD permission to file petitions…” that says “Do you understand this [initial inquiry does constitute an attorney-client relationship]”  I’m sure you at CfA can think of a better way to say that. Ok to incorporate this in existing checkbox.

**Comment by jennifermarie** [comment]
This ticket will involve some working on copy.

**Comment by bengolder** [comment]
![screen shot 2017-02-13 at 7 27 19 pm](https://cloud.githubusercontent.com/assets/451510/22913918/944ed39c-f222-11e6-9ef5-145bceefe934.png)
![screen shot 2017-02-13 at 7 26 56 pm](https://cloud.githubusercontent.com/assets/451510/22913919/945fa406-f222-11e6-9800-2918730b0f81.png)
