### ISSUE TITLE
Solano County - contact info

### ISSUE THREAD

**Issue by sarahlizwhite** [codeforamerica/clear-my-record#480]
Require either e-mail or phone number for applicant contact info. (not just phone number)

**Comment by jennifermarie** [comment]
We need form-level validation of either `phone` or `email` fields.

**Comment by bengolder** [comment]
![screen shot 2017-02-13 at 2 30 26 pm](https://cloud.githubusercontent.com/assets/451510/22906354/fc8c4658-f1f8-11e6-8a8d-17a73b66fd15.png)
