### ISSUE TITLE
Follow up with AR from SF PD

### ISSUE THREAD

**Issue by jazmynlatimer** [codeforamerica/clear-my-record#67]

**Comment by bengolder** [comment]
We should tell AR how the last week went, major lessons learned, and what we need in order to move forward. Getting permission to make a public link is the main priority.

**Comment by bengolder** [comment]
We can present two options: doing it manually vs. the web.

**Comment by bengolder** [comment]
https://docs.google.com/document/d/17pVvGejWLHiyzpDOqkPZAZS1UyxwFrZFJC81mAP_DIo/edit
