### ISSUE TITLE
Talk to Kevin about SEO

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/clear-my-record#77]

**Comment by jazmynlatimer** [comment]
talk about audience, what tool should do and how to structure the design to optimize search

**Comment by bengolder** [comment]
I sent you his email via a Slack DM.

**Comment by bengolder** [comment]
For prep, we should estimate:

1. Who is the target audience - Age, Gender, geography, job title, education level, interests. Try to answer this in short bullets
2. Top 5 One word core phrases that target audience would be searching for to find you. 
3. Top 5 Two word core phrases that target audience would be searching for to find you. 
4. Top 5 hashtags that target audience would be using.

**Comment by bengolder** [comment]
https://docs.google.com/a/codeforamerica.org/document/d/1vH7h_BWdpYGSMleTG8pJ4_WakEdhdlDZ073_sAAf7-U/edit?usp=drive_web
